services:
  personal-portfolio:
    build: .
    container_name: personal-portfolio-app
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
#    entrypoint: ["sleep", "infinity"]
